### ISSUE TITLE
Non-initial tiles aren't animated

### ISSUE THREAD

**Issue by chood-cmu** [gcwhitfield/LinguaLitis#13]
When you click on tiles that aren't part of the initial TileInventory set (i.e. after words are submitted, the tiles that get generated to replace the used ones), they jump instantaneously to/from the staged area.  They should be animated instead.  Probably an easy fix of setting tile.animable = true somewhere.  Not game-breaking, but still a pretty major bug.

**Comment by almutwakel** [comment]
Fixed
